export const RoleEvent = {
  CREATE_ON_REQUEST: "ROLE.CREATE.ON_REQUEST",
  FIND_MANY_ON_REQUEST:"ROLE.FIND.MANY.ON_REQUEST",
  FIND_ON_REQUEST:"ROLE.FIND.ON_REQUEST",
  FIND_ON_RESPONSE:"ROLE.FIND.ON_RESPONSE",
  UPDATE_ON_REQUEST: "ROLE.UPDATE.ON_REQUEST",
  DELETE_ON_REQUEST: "ROLE.DELETE.ON_REQUEST",
  CREATE_SUCCESS: "ROLE.CREATE_SUCCESS"
}